[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = ".next"

[[redirects]]
  from = "https://tierlistlol.netlify.app/*"
  to = "https://tierlist.lol/:splat"
  status = 301
  force = true
